### PR TITLE
fixes #1 use `track.currency()` for Facebook conversions

### LINKED ISSUE #1: Facebook conversions don't pass correct currency
I have been testing using analytics.js and have noticed that conversions with currency are not being tracked properly.

I know what the fix is but can't get `npm test` to work? do i need a particular version of node or npm?

### PR DESCRIPTION
**Pull request by albybarber**
I wanted to write test but couldn't get `npm test` working... Any pointers would be much appreciated

### CODE REVIEW

**Comment by sperand-io** [comment]
Thanks so much, looking good so far!! Would love to add a test too — lmk if switching node versions (we use [`n`](https://github.com/tj/n) here for doing that seamlessly) does the trick to get them running, otherwise I can add the test and get this merged.

**Comment by albybarber** [comment]
@sperand-io I have added some tests and tested that they fail before my changes.
Lets get this merged!

**Comment by albybarber** [comment]
@sperand-io What is the status of this????

**Comment by hankim813** [comment]
closing this since this integration is deprecated.

**Pull request closed without merging**
